<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="155141" started-at="2020-10-23T16:24:04Z" finished-at="2020-10-23T16:26:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="155141" started-at="2020-10-23T16:24:04Z" finished-at="2020-10-23T16:26:39Z">
      <class name="second.Test_DataProvider">
        <test-method status="PASS" signature="doLogin(java.lang.String)[pri:0, instance:second.Test_DataProvider@3745e5c6]" name="doLogin" duration-ms="60723" started-at="2020-10-23T21:54:05Z" data-provider="getData" finished-at="2020-10-23T21:55:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[watch]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="doLogin(java.lang.String)[pri:0, instance:second.Test_DataProvider@3745e5c6]" name="doLogin" duration-ms="93811" started-at="2020-10-23T21:55:06Z" data-provider="getData" finished-at="2020-10-23T21:56:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Laptop]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="FAIL" signature="tear()[pri:0, instance:second.Test_DataProvider@3745e5c6]" name="tear" is-config="true" duration-ms="7" started-at="2020-10-23T21:56:40Z" finished-at="2020-10-23T21:56:40Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerExceptionat second.Test_DataProvider.tear(Test_DataProvider.java:153)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- second.Test_DataProvider -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
